---
- name: Install certbot on RedHat
  when: ansible_os_family == "RedHat"
  block:
    - name: Install epel repo
      ansible.builtin.dnf:
        name: epel-release
    - name: Install certbot
      ansible.builtin.dnf:
        name: certbot
        enablerepo: epel

- name: Install certbot on Debian
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: certbot

- name: Install certbot services
  notify: Restart certbot
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
  loop:
    - certbot-renew.service
    - certbot-renew.timer

- name: Start certbot service
  ansible.builtin.systemd:
    name: certbot-renew.timer
    state: started
    enabled: true

- name: Use letsencrypt
  when: elan_certbot_ca == "letsencrypt"
  block:
    - name: Generate initial certificate
      ansible.builtin.shell:
        cmd: >
          certbot certonly
          --non-interactive
          --authenticator webroot
          --webroot-path /var/lib/nginx/
          --agree-tos
          --email {{ elan_certbot_letsencrypt_email }}
          --domains {{ elan_certbot_domains | join(",") }}
          --cert-name elan-certbot-certificate
        creates: /etc/letsencrypt/live/elan-certbot-certificate/fullchain.pem
      no_log: true
    - name: Expand existing certificate  # noqa: no-changed-when
      when: elan_certbot_expand_existing
      notify: Reload nginx
      ansible.builtin.shell:
        cmd: >
          certbot certonly
          --non-interactive
          --authenticator webroot
          --webroot-path /var/lib/nginx/
          --agree-tos
          --email {{ elan_certbot_letsencrypt_email }}
          --domains {{ elan_certbot_domains | join(",") }}
          --expand
          --cert-name elan-certbot-certificate
      no_log: true

- name: Use sectigo
  when: elan_certbot_ca == "sectigo"
  block:
    - name: Generate initial certificate
      ansible.builtin.shell:
        cmd: >
          certbot certonly
          --standalone
          --non-interactive
          --agree-tos
          --email {{ elan_certbot_letsencrypt_email }}
          --server https://acme.sectigo.com/v2/OV
          --eab-kid {{ elan_certbot_eab_kid }}
          --eab-hmac-key {{ elan_certbot_eab_hmac }}
          --domains {{ elan_certbot_domains | join(",") }}
          --cert-name elan-certbot-certificate
        creates: /etc/letsencrypt/live/elan-certbot-certificate/fullchain.pem
    - name: Expand existing certificate  # noqa: no-changed-when
      when: elan_certbot_expand_existing
      notify: Reload nginx
      ansible.builtin.shell:
        cmd: >
          certbot  certonly
          --standalone
          --non-interactive
          --agree-tos
          --email {{ elan_certbot_letsencrypt_email }}
          --server https://acme.sectigo.com/v2/OV
          --eab-kid {{ elan_certbot_eab_kid }}
          --eab-hmac-key {{ elan_certbot_eab_hmac }}
          --domains {{ elan_certbot_domains | join(",") }}
          --expand
          --cert-name elan-certbot-certificate

- name: Symlink certificates
  notify: Reload nginx
  ansible.builtin.file:
    src: "/etc/letsencrypt/live/elan-certbot-certificate/{{ item.src }}"
    dest: "/etc/nginx/tls/{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: "fullchain.pem"
      dest: "certificate.crt"
    - src: "privkey.pem"
      dest: "certificate.key"
